server:
  port: 9002

# === common.start ===

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost

feign:
  secret:
    key: ${FEIGN_SECRET_KEY}

saga:
  compensate:
    scheduler:
      fixed-delay-string: ${SAGA_COMPENSATE_SCHEDULER_FIXED_DELAY}
      initial-delay-string: ${SAGA_COMPENSATE_SCHEDULER_INITIAL_DELAY}

# === common.end ===

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_USER}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cloud:
    function:
      definition: processUserLoggedInFirstToday;
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        processUserLoggedInFirstToday-in-0:
          destination: UserLoggedInFirstToday.events
